server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/hotelDB
    username: postgres
    password: Szajba1
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false

okta:
  oauth2:
    issuer: https://dev-87163480.okta.com/oauth2/default
    clientId: 0oa6orr3gkY3MOoPX5d7
    clientSecret: gXtAW-chOw0y_LZL5kzrscDby_vPl_UG_7BVwAag
    audience: api://default
    baseUrl: https://dev-87163480.okta.com
    rolesClaim: groups
    redirect-uri: /authorization-code/callback
    postLogoutRedirectUri: http://localhost:8080/


aws:
  access:
    key:
      id: AKIASLSRCJ4LILNP2LQB
  secret:
    access:
      key: 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
  s3:
    region: eu-central-1
    bucket:
      name: hotel-management-s3-bucket
