server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/hotelDB
    username:
    password:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false

okta:
  oauth2:
    issuer:
    clientId:
    clientSecret:
    audience:
    baseUrl:
    rolesClaim: groups
    redirect-uri: /authorization-code/callback
    postLogoutRedirectUri: http://localhost:8080/
    orgUrl:
    clientCredentialsSecret:


aws:
  access:
    key:
      id:
  secret:
    access:
      key:
  s3:
    region: eu-central-1
    bucket:
      name: hotel-management-s3-bucket
